### ISSUE TITLE
8$: warn on assignment to rhs

### ISSUE THREAD

**Issue by strager** [quick-lint/quick-lint-js#1016]
quick-lint-js should warn about code like `x = x;`, i.e. a variable assigned to a variable.

`x.p = x.p;` should *not* warn because there might be side effects. For example, `element.innerHTML = element.innerHTML;` is not a no-op; it removes event listeners.

`x += x;`, `x &&= x;`, etc. should *not* warn.

Docs for creating a diagnostic: https://quick-lint-js.com/contribute/create-diagnostic/

**Comment by holychowders** [comment]
- [X] I claim this for-hire task. I expect payment after I complete this task. I will email the quick-lint-js team if I am assigned this task.

**Comment by holychowders** [comment]
Draft patch submission: #1031

## TODO

- [ ] Tests pass locally
  - [X] Assert `x = x;` warns
  - [ ] Assert `x.p = x.p;` doesn't warn
  - [X] Assert `x += x;` doesn't warn
  - [X] Assert `x &&= x;` doesn't warn
- [ ] Code is formatted
- [X] Tests added 
- [X] Documentation is updated
- [X] Code is checked into Git as one commit or a small number of commits
- [X] Commits have a description explaining what the problem was and what the solution is
- [ ] The first line of the commit follows Conventional Commits
- [ ] Check that squigglies work

## Requesting Help

- Need help ensuring that `x.p = x.p;` does not warn.
- May need help getting my changes formatted with `clang-format` version 9
