### ISSUE TITLE
Support non-ASCII Unicode

### ISSUE THREAD

**Issue by strager** [quick-lint/quick-lint-js#42]
quick-lint-js should support UTF-8 input files, not just ASCII input files.

- [x] Non-ASCII in identifiers (#64)
- [x] Non-ASCII in identifier escapes (#62)
- [x] Non-ASCII in string and template literals
- [x] Non-ASCII in comments
- [x] Non-ASCII in horizontal whitespace
- [x] Non-ASCII line terminators
- [x] Column numbers if line contains non-ASCII characters (#63)

**Comment by strager** [comment]
We don't validate UTF-8 in string literals, template literals, regular expression literals, or comments. We probably should. But maybe later.

**Comment by strager** [comment]
I filed issue #98 for validation outside identifiers.
